branches:
  only:
    - master
matrix:
  include:
    # server
    - language: node_js
      node_js:
        - "9"
      cache:
        timeout: 300
        directories:
        - $HOME/.npm
      before_install:
        - npm install -g npm
      install:
        - (cd server && npm install)
      script:
        - (cd server && make build)

notifications:
  email: false
